version: 2
updates:
  # version updates: enabled
  # security updates: enabled
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "cicd"
    schedule:
      interval: "daily"


  # version updates: enabled
  # security updates: enabled
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1
